In [ ]:
# Import Library

In [1]:
!ls

members.csv.7z	  sample_submission.csv.7z  songs.csv.7z  train.csv.7z
ML_Project.ipynb  song_extra_info.csv.7z    test.csv.7z

In [ ]:
#!sudo apt-get install p7zip-full

In [20]:
!7z e members.csv.7z

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: members.csv.7z

Extracting  members.csv

Everything is Ok

Size:       2503827
Compressed: 1349856

In [21]:
!ls

members.csv	ML_Project.ipynb	  song_extra_info.csv.7z  test.csv.7z
members.csv.7z	sample_submission.csv.7z  songs.csv.7z		  train.csv.7z

In [22]:
!7z e song_extra_info.csv.7z
!7z e test.csv.7z
!7z e sample_submission.csv.7z
!7z e songs.csv.7z
!7z e train.csv.7z

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: song_extra_info.csv.7z

Extracting  song_extra_info.csv

Everything is Ok

Size:       181010294
Compressed: 103608205

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: test.csv.7z

Extracting  test.csv

Everything is Ok

Size:       347789925
Compressed: 43925208

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: sample_submission.csv.7z

Extracting  sample_submission.csv

Everything is Ok

Size:       29570380
Compressed: 463688

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: songs.csv.7z

Extracting  songs.csv

Everything is Ok

Size:       221828666
Compressed: 105809525

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)

Processing archive: train.csv.7z

Extracting  train.csv

Everything is Ok

Size:       971675848
Compressed: 106420688

In [23]:
!ls

members.csv	       sample_submission.csv.7z  songs.csv.7z  train.csv.7z
members.csv.7z	       song_extra_info.csv	 test.csv
ML_Project.ipynb       song_extra_info.csv.7z	 test.csv.7z
sample_submission.csv  songs.csv		 train.csv

In [24]:
import numpy as np
import pandas as pd

In [27]:
train=pd.read_csv('train.csv')

In [28]:
train.head()

,msno,song_id,source_system_tab,source_screen_name,source_type,target
0,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,BBzumQNXUHKdEBOB7mAJuzok+IJA1c2Ryg/yzTF6tik=,explore,Explore,online-playlist,1
1,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,bhp/MpSNoqoxOIB+/l8WPqu6jldth4DIpCm3ayXnJqM=,my library,Local playlist more,local-playlist,1
2,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,JNWfrrC7zNN7BdMpsISKa4Mw+xVJYNnxXh3/Epw7QgY=,my library,Local playlist more,local-playlist,1
3,Xumu+NIjS6QYVxDS4/t3SawvJ7viT9hPKXmf0RtLNx8=,2A87tzfnJTSWqD7gIZHisolhe4DMdzkbd6LzO1KHjNs=,my library,Local playlist more,local-playlist,1
4,FGtllVqz18RPiwJj/edr2gV78zirAiY/9SmYvia+kCg=,3qm6XTZ6MOCU11x8FIVbAGH5l5uMkT3/ZalWG1oo2Gc=,explore,Explore,online-playlist,1

train.csv

msno: user id

song_id: song id

source_system_tab: the name of the tab where the event was triggered. System tabs are used to categorize KKBOX mobile apps functions. For example, tab my library contains functions to manipulate the local storage, and tab search contains functions relating to search.

source_screen_name: name of the layout a user sees.

source_type: an entry point a user first plays music on mobile apps. An entry point could be album, online-playlist, song .. etc.

target: this is the target variable. target=1 means there are recurring listening event(s) triggered within a month after the user’s very first observable listening event, target=0 otherwise .

In [51]:
print("Data distribution (T/F):",np.mean(train.target))
print("Total Items in Train:",len(train.target))
print("Distinct Users in train:",len(np.unique(train.msno)))
print("Distinct Songs in train:",len(np.unique(train.song_id)))

Data distribution (T/F): 0.5035170841614234
Total Items in Train: 7377418
Distinct Users in train: 30755
Distinct Songs in train: 359966

In [50]:
print("Distinct source_system_tab in train:",len(np.unique(train.source_system_tab.astype('str'))))
print("Distinct source_screen_name in train:",len(np.unique(train.source_screen_name.astype('str'))))
print("Distinct source_type in train:",len(np.unique(train.source_type.astype('str'))))

Distinct source_system_tab in train: 9
Distinct source_screen_name in train: 21
Distinct source_type in train: 13

In [57]:
#NA entries
train.isnull().astype('int').sum(axis=0)

msno                       0
song_id                    0
source_system_tab      24849
source_screen_name    414804
source_type            21539
target                     0
dtype: int64

In [58]:
total_items=len(train.target)

In [60]:
# NA percentages
print("source_system_tab :",train.source_system_tab.isnull().astype('int').sum(axis=0)*100/total_items)
print("source_screen_name :",train.source_screen_name.isnull().astype('int').sum(axis=0)*100/total_items)
print("source_type  :",train.source_type.isnull().astype('int').sum(axis=0)*100/total_items)

source_system_tab : 0.3368251602389888
source_screen_name : 5.622617560778039
source_type  : 0.2919585144829804

In [65]:
len(train.dropna())

6959297

In [68]:
train_data_WNA=train.dropna()
print("Left items:",len(train_data_WNA))

Left items: 6959297

In [69]:
train_data_WNA.isnull().astype('int').sum(axis=0)

msno                  0
song_id               0
source_system_tab     0
source_screen_name    0
source_type           0
target                0
dtype: int64

In [70]:
member=pd.read_csv('members.csv')
member.head()

,msno,city,bd,gender,registered_via,registration_init_time,expiration_date
0,XQxgAYj3klVKjR3oxPPXYYFp4soD4TuBghkhMTD4oTw=,1,0,NaN,7,20110820,20170920
1,UizsfmJb9mV54qE9hCYyU07Va97c0lCRLEQX3ae+ztM=,1,0,NaN,7,20150628,20170622
2,D8nEhsIOBSoE6VthTaqDX8U6lqjJ7dLdr72mOyLya2A=,1,0,NaN,4,20160411,20170712
3,mCuD+tZ1hERA/o5GPqk38e041J8ZsBaLcu7nGoIIvhI=,1,0,NaN,9,20150906,20150907
4,q4HRBfVSssAFS9iRfxWrohxuk9kCYMKjHOEagUMV6rQ=,1,0,NaN,4,20170126,20170613

members.csv

user information.

msno

city

bd: age. Note: this column has outlier values, please use your judgement.

gender

registered_via: registration method

registration_init_time: format %Y%m%d

expiration_date: format %Y%m%d

In [88]:
def summary(df):
    print("Total number of records: ",len(df))
    for i in df.columns:
        print('Distinct {} in train: {}'.format(i,len(np.unique(df[i].astype('str')))))

In [89]:
summary(member)

Total number of records:  34403
Distinct msno in train: 34403
Distinct city in train: 21
Distinct bd in train: 95
Distinct gender in train: 3
Distinct registered_via in train: 6
Distinct registration_init_time in train: 3862
Distinct expiration_date in train: 1484

In [90]:
member.describe()

,city,bd,registered_via,registration_init_time,expiration_date
count,34403.000000,34403.000000,34403.000000,3.440300e+04,3.440300e+04
mean,5.371276,12.280935,5.953376,2.013994e+07,2.016901e+07
std,6.243929,18.170251,2.287534,2.954015e+04,7.320925e+03
min,1.000000,-43.000000,3.000000,2.004033e+07,1.970010e+07
25%,1.000000,0.000000,4.000000,2.012103e+07,2.017020e+07
50%,1.000000,0.000000,7.000000,2.015090e+07,2.017091e+07
75%,10.000000,25.000000,9.000000,2.016110e+07,2.017093e+07
max,22.000000,1051.000000,16.000000,2.017023e+07,2.020102e+07

In [91]:
np.unique(member.registered_via)

array([ 3,  4,  7,  9, 13, 16])

In [92]:
np.unique(member.city)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22])

In [117]:
def count_na(df):
    new=pd.DataFrame(df.isnull().astype('int').sum(axis=0),columns=["NA_count"])
    new['Percentage']=df.isnull().astype('int').sum(axis=0)*100/len(df)
    return new

count_na(member)

In [119]:
songs=pd.read_csv('songs.csv')
songs.head()

,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=,247640,465,張信哲 (Jeff Chang),董貞,何啟弘,3.0
1,o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=,197328,444,BLACKPINK,TEDDY| FUTURE BOUNCE| Bekuh BOOM,TEDDY,31.0
2,DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=,231781,465,SUPER JUNIOR,NaN,NaN,31.0
3,dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=,273554,465,S.H.E,湯小康,徐世珍,3.0
4,W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=,140329,726,貴族精選,Traditional,Traditional,52.0

songs.csv
The songs. Note that data is in unicode.

song_id

song_length: in ms

genre_ids: genre category. Some songs have multiple genres and they are separated by |

artist_name

composer

lyricist

language

In [121]:
summary(songs)

Total number of records:  2296320
Distinct song_id in train: 2296320
Distinct song_length in train: 146534
Distinct genre_ids in train: 1046
Distinct artist_name in train: 222363
Distinct composer in train: 329824
Distinct lyricist in train: 110926
Distinct language in train: 11

In [122]:
songs.head(50)

,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=,247640,465,張信哲 (Jeff Chang),董貞,何啟弘,3.0
1,o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=,197328,444,BLACKPINK,TEDDY| FUTURE BOUNCE| Bekuh BOOM,TEDDY,31.0
2,DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=,231781,465,SUPER JUNIOR,NaN,NaN,31.0
3,dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=,273554,465,S.H.E,湯小康,徐世珍,3.0
4,W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=,140329,726,貴族精選,Traditional,Traditional,52.0
5,kKJ2JNU5h8rphyW21ovC+RZU+yEHPM+3w85J37p7vEQ=,235520,864|857|850|843,貴族精選,Joe Hisaishi,Hayao Miyazaki,17.0
6,N9vbanw7BSMoUgdfJlgX1aZPE1XZg8OS1wf88AQEcMc=,226220,458,伍佰 & China Blue,Jonathan Lee,NaN,3.0
7,GsCpr618xfveHYJdo+E5SybrpR906tsjLMeKyrCNw8s=,276793,465,光良 (Michael Wong),光良,彭資閔,3.0
8,oTi7oINPX+rxoGp+3O6llSltQTl80jDqHoULfRoLcG4=,228623,465,林俊傑 (JJ Lin),JJ Lin,Wu Qing Feng,3.0
9,btcG03OHY3GNKWccPP0auvtSbhxog/kllIIOx5grE/k=,232629,352|1995,Kodaline,Stephen Garrigan| Mark Prendergast| Vincent Ma...,Stephen Garrigan| Mark Prendergast| Vincent Ma...,52.0
10,HulM/OaHgD5kUyjNQjDUf8VZdsy7h4EJUIff79Cifwo=,272544,2157,D.L 羅時豐 (Daniel Lo),陳偉強,陳偉強,10.0
11,wypPzqFNdUJAqyBVxmFGaK4z7krUNWr5YqA0q0wi9eE=,254880,465,白安 (Ann),白安,白安,3.0
12,fAZLdfQaLG76a6Ei4alt1eSjBM9rshQkiQEC6+n+y08=,180871,726,Littlesong,Michael William Balfe,NaN,-1.0
13,tqBlH4r/q1Tf6C5+C6ucjGlLjMbfu5yjqB6ifRzy5dc=,257602,458,蔡旻佑 (Evan Yo),蔡旻佑,陳信延,3.0
14,an6EdIr+Z+KbqIVQiXn5PKkcXncefQ7hhWONseRuub4=,282697,359,Coldplay,Chris Martin| Guy Berryman| Jonny Buckland| Mi...,NaN,52.0
15,J2MFmy8iF94mExWfRWE3KxsMZB+ZIedV5liqZoSrERQ=,221518,359,Maggie Rogers,Maggie Rogers| Nicholas Das,NaN,52.0
16,MrRilXQwoUAcoAf0N3RT82qX2/us/wEhYDXE+ZTIW5o=,199157,458,小男孩樂團 (Men Envy Children),"Skot Suyama陶山/""蔡詩蕓 Dominique Tsai""",程懷昌 Vince Cheng,3.0
17,OcG4Ya7iXmVMCMy24C5wxDMtr9w6WQZiFaN0uq6zdTk=,169430,465,BIGBANG,TAEYANG| TEDDY,G-DRAGON| T.O.P| TEDDY,3.0
18,JcHIgDP5ivyqYIn7RxfXM13eWwOzcoxkWosSauz6RbU=,374027,726,White Noise,NaN,NaN,-1.0
19,3Po6v5nAk+ACnmTgGF4maCQNwWCuCT9BSR13M5c8KG8=,246015,465,步步驚心主題曲原聲EP,嚴藝丹,嚴藝丹,3.0
20,IV8kTOBKcUoO4fINEi+VTYzr7TdyM/kin+gapgzygco=,228993,465,Katy Perry,Katy Perry| Max Martin| Lukasz Gottwald| Henry...,NaN,52.0
21,XtT+taE0f0Ua5O96nZ48vW+r8YwRgO6WdWOoJmmDUNU=,226951,465,劉若英 (Rene Liu),張起政,廖瑩如,3.0
22,XVdugYtHPN1vCK/8rsZZj/5MX8wv421d4unsaOpPq7I=,292571,465,傅又宣 (Maggie Fu),陶山,方文山,3.0
23,FZ5/wgtMuMV0Y8gzzgQj6bH3Qpr62zRV/LwbhNBrdqk=,220056,465,BIGBANG TAEYANG,NaN,NaN,31.0
24,bTM25FJNlCHnltU0hhQDFAzdnOYsobmfCwwAnN1K2a8=,430080,1609,Danny Marquez & Ferry B,NaN,NaN,52.0
25,SONqxocCptA85J/tJ1hGlTVbQxs+x1gokyes79xZFO0=,266788,1609,Kyary Pamyu Pamyu (きゃりーぱみゅぱみゅ),Yasutaka Nakata,Yasutaka Nakata,17.0
26,Co8PcF2DeW+i14x4xSwe7YFkJKAm1B8SZNXdVTpsljc=,240326,465,品冠 (Victor Wong),品冠,戴佩妮,3.0
27,+M/yM08pYwOznHRvf9Aj95A9M85wn4/jsTX0ye1KR2c=,281054,139,The Weeknd,Abel Tesfaye| Timothy Mckenzie| Carlo Montagnese,NaN,52.0
28,+dOlHQGlsiHPbG1cMYsoFVsAi05YgsGfeEzsdS16yec=,368441,1609,Marvin Gaye & Kygo,Marvin Gaye| Odell Brown| David Ritz,Marvin Gaye| Odell Brown| David Ritz,-1.0
29,gG3/58uZyyOwaPT+eGWL81mwCzcDPW2EmwYcjWmvJSs=,226742,465,五月天 (Mayday),阿信,阿信,3.0
30,i0JD8QBIkZtIoe0NvVQkGxDZGdRYPQ8woEL7dcaloxE=,212276,465,謝霆鋒 (Nicholas Tse),NaN,NaN,24.0
31,Sh6niIO6WYyFZbTX66CmEW8GphrK8tdmm3mpEpJL2dg=,190566,465,黃鴻升 (Alien Huang),康友韋,黃鴻升,3.0
32,N9wIY8MsBg4ctaiivtDCvk1ynsMtIbX9TpjkwEfidcE=,342144,465,HUSH,HUSH,HUSH,3.0
33,uHSNhmCD4V7IglA225OelhM+HreWIjFdE+nf3NicFOU=,394739,1609,Pet Shop Boys,NaN,NaN,52.0
34,QXxwXFuL2yNKyn2NM68uV7RJ2AaJukZeGPvu+y6kCJU=,238132,458,陳大天 (Daniel Chen),阿達/廖偉傑,陳大天,3.0
35,NV9HhUzyK50tGvxb3w0PdZoaw3Ypp86XDmmMr0vgFdg=,262749,139,John Legend,John Stephens,John Stephens,52.0
36,PFTxx8m3p9Sy3z0tkE/Tfysm4c4AXGSNTzVY6FM/Qag=,244819,458,A-Lin,金大洲,鄔裕康,3.0
37,fL+kYiefBmixA+rraUsD9svI5GrPBM1yUVmuft4cZVU=,235488,458,花兒 (林佳音),周佳佑,周佳佑,3.0
38,mHwy8WSNpd4E03pxeZ2vZJOSwFyjI9D/q8MpD2qpQ2k=,223294,NaN,李玉璽 (Dino Lee),李玉璽,李玉璽,3.0
39,OLnB6amnCTMEz5KxrV7pdkXJWB+fnMoWVJSzv2AlBLk=,236355,465,Westlife,Bettis| Hammond,Bettis| Hammond,52.0
40,vzWZd7svSo4Xc/kUMEtRuAJkupQIGqcPeTqESWz84UQ=,196179,465,JUNIEL,TWO FACE | 이상호 (Lee Sang Ho),한성호 (Han Sung Ho),31.0
41,DhAkZvlnryiYENIhuxu1FtJeYJzmEZxDBQO8qaxx/hY=,290110,465,蔡旻佑 (Evan Yo),蔡旻佑,陳信延/蔡旻佑,3.0
42,aoojHrvDew9JNvFIVh9b7DQtdCIk44GwF6hrvjl+Eb0=,299816,139,Mary J. Blige,Mary J. Blige| Charles Hinshaw Jr| Brandon Ale...,NaN,52.0
43,igUq5ErBzlm2Wi05YsoiyWdxd4wbHGPaFOS8kQFhoik=,228717,465,Urban Zakapa,Gwon Soonil| Park Yongin| Choi JaeMan| Jo HyunAh,Gwon Soonil| Park Yongin| Choi JaeMan| Jo HyunAh,31.0
44,/pNJtPeT5RixL9cwAScQ83XG6lzNjQbxXdz9Bxm3UCk=,954851,873,蘇曼竹巴仁波切,公版,公版,-1.0
45,v27+O2w69lwrw/luclRexIr/mdGNCJJp/EBhmsLje40=,246491,465,吳克群 (Kenji Wu),吳克羣,吳克羣,3.0
46,3QZAIrm2XJ747bKJJSAMQ0yTsyX8JvXKI3JdGswnO7g=,207261,465,SUPER JUNIOR-M,NaN,NaN,3.0
47,dzAyth7bpVgPJ7ACTj/lnj6gXYJV1Yo9aetyqb1+lps=,333635,465,蔡健雅 (Tanya Chua),蔡健雅,蔡健雅,3.0
48,SpfSYkFYITvbQNXXtTSIWmpJLcYrnhg0oMq5g/9MM4U=,136907,1955,Motörhead,NaN,NaN,52.0
49,8fGQPXFKMW+0O4VMCbU8H6jUDeeRJerCvk++yjXcztM=,111966,465,Schnappi(Joy),NaN,NaN,52.0

In [127]:
lengths=[len(i.split('|')) for i in songs.genre_ids.astype('str')]

In [128]:
np.unique(lengths)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [129]:
from collections import Counter
Counter(lengths)

Counter({1: 2123444,
         4: 8748,
         2: 138833,
         3: 24064,
         5: 1068,
         7: 62,
         6: 90,
         8: 11})

In [130]:
count_na(songs)

             NA_count  Percentage
song_id             0    0.000000
song_length         0    0.000000
genre_ids       94116    4.098558
artist_name         0    0.000000
composer      1071354   46.655257
lyricist      1945268   84.712409
language            1    0.000044

In [132]:
extra_song=pd.read_csv('song_extra_info.csv')
extra_song.head()

                                        song_id             name          isrc
0  LP7pLJoJFBvyuUwvu+oLzjT+bI+UeBPURCecJsX1jjs=               我們  TWUM71200043
1  ClazTFnk6r0Bnuie44bocdNMM3rdlrq0bCGAsGUWcHE=  Let Me Love You  QMZSY1600015
2  u2ja/bZE3zhCGxvbbOB3zOoUjx27u40cf5g09UXMoKQ=              原諒我  TWA530887303
3  92Fqsy0+p6+RHe2EoLKjHahORHR1Kq1TBJoClW9v+Ts=          Classic  USSM11301446
4  0QFmz/+rJy1Q56C1DuYqT9hKKqi5TUqx0sN0IwvoHrw=             愛投羅網  TWA471306001

song_extra_info.csv

song_id

song name - the name of the song.

isrc - International Standard Recording Code, theoretically can be used as an identity of a song. However, what 
worth to note is, ISRCs generated from providers have not been officially verified; therefore the information in ISRC, such as country code and reference year, can be misleading/incorrect. Multiple songs could share one ISRC since a single recording could be re-published several times.

In [133]:
summary(extra_song)

Total number of records:  2295971
Distinct song_id in train: 2295971
Distinct name in train: 1168980
Distinct isrc in train: 1806826

In [134]:
count_na(extra_song)

         NA_count  Percentage
song_id         0    0.000000
name            2    0.000087
isrc       136548    5.947288

In [137]:
test=pd.read_csv("test.csv")
test.head()

,id,msno,song_id,source_system_tab,source_screen_name,source_type
0,0,V8ruy7SGk7tDm3zA51DPpn6qutt+vmKMBKa21dp54uM=,WmHKgKMlp1lQMecNdNvDMkvIycZYHnFwDT72I5sIssc=,my library,Local playlist more,local-library
1,1,V8ruy7SGk7tDm3zA51DPpn6qutt+vmKMBKa21dp54uM=,y/rsZ9DC7FwK5F2PK2D5mj+aOBUJAjuu3dZ14NgE0vM=,my library,Local playlist more,local-library
2,2,/uQAlrAkaczV+nWCd2sPF2ekvXPRipV7q0l+gbLuxjw=,8eZLFOdGVdXBSqoAv5nsLigeH2BvKXzTQYtUM53I0k4=,discover,NaN,song-based-playlist
3,3,1a6oo/iXKatxQx4eS9zTVD+KlSVaAFbTIqVvwLC1Y0k=,ztCf8thYsS4YN3GcIL/bvoxLm/T5mYBVKOO4C9NiVfQ=,radio,Radio,radio
4,4,1a6oo/iXKatxQx4eS9zTVD+KlSVaAFbTIqVvwLC1Y0k=,MKVMpslKcQhMaFEgcEQhEfi5+RZhMYlU3eRDpySrH8Y=,radio,Radio,radio

In [138]:
summary(test)

Total number of records:  2556790
Distinct id in train: 2556790
Distinct msno in train: 25131
Distinct song_id in train: 224753
Distinct source_system_tab in train: 9
Distinct source_screen_name in train: 23
Distinct source_type in train: 13

In [141]:
#test users not in training
len(np.setdiff1d(test.msno.unique(),train.msno.unique()))

3648

In [155]:
#test song ids not in train
#len(np.setdiff1d(test.song_id.unique(),train.song_id.unique()))

1